## Pokemon Arceus: Legends Stats Webscraper

Goal is to obtain the Pokemon stats from the Pokemon Arceus Legends game released in 2022. I webscrape with Python & Selenium from the arceus.gg website.

In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
from selenium import webdriver
import datetime
import time

In [2]:
# arceus.gg website:

url = 'https://www.arceus.gg/'

In [3]:
# Open up arceus.gg website:

driver = webdriver.Chrome('C:\Program Files (x86)\chromedriver.exe')
driver.get(url)

# Maximize Window:
driver.maximize_window()
driver.implicitly_wait(5)

Go through each Pokemon (class: pokemon__list__link) and obtain:

* Pokedex Number
* Pokemon Name
* Types
* Base Stats

**Base Stats**

* HP
* Attack
* Defense
* Sp. Atk
* Sp Def
* Speed

## Test On Rowlet

In [4]:
# URL: "https://www.arceus.gg/pokemon/rowlet/"

rowlet_url = driver.find_element_by_xpath('//*[@id="gatsby-focus-wrapper"]/div[3]/main/ul/a[1]').get_attribute('href')

In [5]:
# Go to Rowlet URL
driver.get(rowlet_url)

In [6]:
# Get Name:

rowlet_name = driver.find_element_by_xpath("//*[@class='app__page__title']")

In [7]:
rowlet_name.text.replace('Pok√©mon Legends: Arceus ', '')

'Rowlet'

In [8]:
# Pokemon Number

rowlet_number = driver.find_element_by_xpath('//*[@class="pokemon__number"]')

In [9]:
rowlet_number.text

'#001'

In [10]:
rowlet_number.text.replace('#', '')

'001'

In [11]:
# Types:
rowlet_types = driver.find_element_by_xpath('//*[@class="pokemon__info__types"]')

In [12]:
rowlet_types.text.split('\n')

['GRASS', 'FLYING']

In [13]:
# Type One:

driver.find_element_by_xpath('//*[@class="pokemon__info__types"]/div[1]/h3').text

'GRASS'

In [14]:
# Type Two:

try:
    test = driver.find_element_by_xpath('//*[@class="pokemon__info__types"]/div[2]/h3').text
    print(f"'{test}'")
except:
    print("N/A")

'FLYING'

In [15]:
# Hp
rowlet_hp = driver.find_element_by_xpath('//*[@class="pokemon__stat__key"][contains(text(), "HP")]/following-sibling::div[2]')

rowlet_hp.text

'68'

In [16]:
# Rowlet Attack
rowlet_atk = driver.find_element_by_xpath('//*[@class="pokemon__stat__key"][contains(text(), "Attack")]/following-sibling::div[2]')

rowlet_atk.text

'55'

In [17]:
# Rowlet Defense
rowlet_def = driver.find_element_by_xpath('//*[@class="pokemon__stat__key"][contains(text(), "Defense")]/following-sibling::div[2]')

rowlet_def.text

'55'

In [18]:
# Rowlet Sp Atk
rowlet_sp_atk = driver.find_element_by_xpath('//*[@class="pokemon__stat__key"][contains(text(), "Sp. Atk")]/following-sibling::div[2]')

rowlet_sp_atk.text

'50'

In [19]:
# Rowlet Sp Def
rowlet_sp_def = driver.find_element_by_xpath('//*[@class="pokemon__stat__key"][contains(text(), "Sp. Def")]/following-sibling::div[2]')

rowlet_sp_def.text

'50'

In [20]:
# Rowlet Speed
rowlet_speed = driver.find_element_by_xpath('//*[@class="pokemon__stat__key"][contains(text(), "Speed")]/following-sibling::div[2]')

rowlet_speed.text

'42'

In [21]:
# Total Base Stats
rowlet_total_stats = driver.find_element_by_xpath('//*[@class="pokemon__stat pokemon__stat--total"]/b')

rowlet_total_stats.text

'320'

## Loop Through All 242 Pokemon

In [22]:
# arceus.gg website:

url = 'https://www.arceus.gg/'

In [23]:
# Open up arceus.gg website:

driver = webdriver.Chrome('C:\Program Files (x86)\chromedriver.exe')
driver.get(url)

# Maximize Window:
driver.maximize_window()
driver.implicitly_wait(5)

In [24]:
## Scrape information from arceus.gg

# Initialize lists:
number_list = []
pokemon_list = []
poke_type_one = []
poke_type_two = []
hp_list = []
attack_list = []
defense_list = []
sp_atk_list = []
sp_def_list = []
speed_list = []
total_stats_list = []

# Pokemon links
pokemon_links = [x.get_attribute("href") for x 
                 in driver.find_elements_by_xpath('//*[@class = "pokemon__list__link"]')]

for link in pokemon_links:
    driver.implicitly_wait(3)

    try:
        driver.get(link)
        driver.implicitly_wait(2)
    except:
        None
        
    # Get Pokemon Numbers
    try:
        num = driver.find_element_by_xpath('//*[@class="pokemon__number"]')
        number_list.append(num.text.replace('#', ''))
    except:
        number_list.append('N/A')
    driver.implicitly_wait(2)
    
    # Get Pokemon Name:
    try:
        name = driver.find_element_by_xpath("//*[@class='app__page__title']")
        pokemon_list.append(name.text.replace('Pok√©mon Legends: Arceus ', ''))
    except:
        pokemon_list.append('N/A')
    driver.implicitly_wait(2)
    
    # Pokemon type 1:
    try:
        type_one = driver.find_element_by_xpath('//*[@class="pokemon__info__types"]/div[1]/h3').text
        poke_type_one.append(type_one)
    except:
        poke_type_one.append('N/A')
    driver.implicitly_wait(2)
    
    # Pokemon type 2:
    try:
        type_two = driver.find_element_by_xpath('//*[@class="pokemon__info__types"]/div[2]/h3').text
        poke_type_two.append(type_two)
    except:
        poke_type_two.append('N/A')
    driver.implicitly_wait(2)
    
    # HP
    try:
        hp = driver.find_element_by_xpath('//*[@class="pokemon__stat__key"][contains(text(), "HP")]/following-sibling::div[2]')
        hp_list.append(hp.text)
    except:
        hp_list.append('N/A')
    driver.implicitly_wait(2)
    
    # Attack
    try:
        atk = driver.find_element_by_xpath('//*[@class="pokemon__stat__key"][contains(text(), "Attack")]/following-sibling::div[2]')
        attack_list.append(atk.text)
    except:
        attack_list.append('N/A')
    driver.implicitly_wait(2)
    
    # Defense
    try:
        defense = driver.find_element_by_xpath('//*[@class="pokemon__stat__key"][contains(text(), "Defense")]/following-sibling::div[2]')
        defense_list.append(defense.text)
    except:
        defense_list.append('N/A')
    driver.implicitly_wait(2)
    
    # Special Attack
    try:
        sp_atk = driver.find_element_by_xpath('//*[@class="pokemon__stat__key"][contains(text(), "Sp. Atk")]/following-sibling::div[2]')
        sp_atk_list.append(sp_atk.text)
    except:
        sp_atk_list.append('N/A')
    driver.implicitly_wait(2)
    
    # Special Defense
    try:
        sp_def = driver.find_element_by_xpath('//*[@class="pokemon__stat__key"][contains(text(), "Sp. Def")]/following-sibling::div[2]')
        sp_def_list.append(sp_def.text)
    except:
        sp_def_list.append('N/A')
    driver.implicitly_wait(2)
    
    # Speed
    try:
        speed = driver.find_element_by_xpath('//*[@class="pokemon__stat__key"][contains(text(), "Speed")]/following-sibling::div[2]')
        speed_list.append(speed.text)
    except:
        speed_list.append('N/A')
    driver.implicitly_wait(2)
    
    # Total Base Stats
    try:
        total_stats = driver.find_element_by_xpath('//*[@class="pokemon__stat pokemon__stat--total"]/b')
        total_stats_list.append(total_stats.text)
    except:
        total_stats_list.append('N/A')
    driver.implicitly_wait(2)

In [25]:
driver.close()

In [26]:
pokemon_links[0:10]

['https://www.arceus.gg/pokemon/rowlet/',
 'https://www.arceus.gg/pokemon/dartrix/',
 'https://www.arceus.gg/pokemon/decidueye-hisuian/',
 'https://www.arceus.gg/pokemon/cyndaquil/',
 'https://www.arceus.gg/pokemon/quilava/',
 'https://www.arceus.gg/pokemon/typhlosion-hisuian/',
 'https://www.arceus.gg/pokemon/oshawott/',
 'https://www.arceus.gg/pokemon/dewott/',
 'https://www.arceus.gg/pokemon/samurott-hisuian/',
 'https://www.arceus.gg/pokemon/bidoof/']

In [27]:
# Change to title case for pokemon types:

poke_type_one = [x.title() for x in poke_type_one]
poke_type_two = [x.title() for x in poke_type_two]

In [28]:
# Change strings into integers:

number_list = [int(x) for x in number_list]
hp_list = [int(x) for x in hp_list]
attack_list = [int(x) for x in attack_list]
defense_list = [int(x) for x in defense_list]

sp_atk_list = [int(x) for x in sp_atk_list]
sp_def_list = [int(x) for x in sp_def_list]
speed_list = [int(x) for x in speed_list]
total_stats_list = [int(x) for x in total_stats_list]

In [29]:
## Create dataframe:

pokemon_arceus_legends_df = pd.DataFrame({
    'Number': number_list,
    'Pokemon': pokemon_list,
    'Type One': poke_type_one,
    'Type Two': poke_type_two,
    'HP': hp_list,
    'Attack': attack_list,
    'Defense': defense_list,
    'Sp. Atk': sp_atk_list,
    'Sp. Def': sp_def_list,
    'Speed': speed_list,
    'Total Stats': total_stats_list
})

In [30]:
pokemon_arceus_legends_df.head(20)

,Number,Pokemon,Type One,Type Two,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total Stats
0,1,Rowlet,Grass,Flying,68,55,55,50,50,42,320
1,2,Dartrix,Grass,Flying,78,75,75,70,70,52,420
2,3,Decidueye Hisuian,Grass,Fighting,88,112,80,95,95,60,530
3,4,Cyndaquil,Fire,N/A,39,52,43,60,50,65,309
4,5,Quilava,Fire,N/A,58,64,58,80,65,80,405
5,6,Typhlosion Hisuian,Fire,Ghost,73,84,78,119,85,95,534
6,7,Oshawott,Water,N/A,55,55,45,63,45,45,308
7,8,Dewott,Water,N/A,75,75,60,83,60,60,413
8,9,Samurott Hisuian,Water,Dark,90,108,80,100,65,85,528
9,10,Bidoof,Normal,N/A,59,45,40,35,40,31,250
10,11,Bibarel,Normal,Water,79,85,60,55,60,71,410
11,12,Starly,Normal,Flying,40,55,30,30,30,60,245
12,13,Staravia,Normal,Flying,55,75,50,40,40,80,340
13,14,Staraptor,Normal,Flying,85,120,70,50,60,100,485
14,15,Shinx,Electric,N/A,45,65,34,40,34,45,263
15,16,Luxio,Electric,N/A,60,85,49,60,49,60,363
16,17,Luxray,Electric,N/A,80,120,79,95,79,70,523
17,18,Wurmple,Bug,N/A,45,45,35,20,30,20,195
18,19,Silcoon,Bug,N/A,50,35,55,25,25,15,205
19,20,Beautifly,Bug,Flying,60,70,50,100,50,65,395

## Save Dataframe to .csv

In [31]:
pokemon_arceus_legends_df.to_csv("Pokemon_Legends_Arceus_Stats.csv", index=False)

# Data Analysis

In [32]:
# Load data:

df = pd.read_csv("Pokemon_Legends_Arceus_Stats.csv", index_col = 0)

In [33]:
df.head(20)

,Pokemon,Type One,Type Two,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total Stats
Number,,,,,,,,,,
1,Rowlet,Grass,Flying,68,55,55,50,50,42,320
2,Dartrix,Grass,Flying,78,75,75,70,70,52,420
3,Decidueye Hisuian,Grass,Fighting,88,112,80,95,95,60,530
4,Cyndaquil,Fire,NaN,39,52,43,60,50,65,309
5,Quilava,Fire,NaN,58,64,58,80,65,80,405
6,Typhlosion Hisuian,Fire,Ghost,73,84,78,119,85,95,534
7,Oshawott,Water,NaN,55,55,45,63,45,45,308
8,Dewott,Water,NaN,75,75,60,83,60,60,413
9,Samurott Hisuian,Water,Dark,90,108,80,100,65,85,528
10,Bidoof,Normal,NaN,59,45,40,35,40,31,250
11,Bibarel,Normal,Water,79,85,60,55,60,71,410
12,Starly,Normal,Flying,40,55,30,30,30,60,245
13,Staravia,Normal,Flying,55,75,50,40,40,80,340
14,Staraptor,Normal,Flying,85,120,70,50,60,100,485
15,Shinx,Electric,NaN,45,65,34,40,34,45,263
16,Luxio,Electric,NaN,60,85,49,60,49,60,363
17,Luxray,Electric,NaN,80,120,79,95,79,70,523
18,Wurmple,Bug,NaN,45,45,35,20,30,20,195
19,Silcoon,Bug,NaN,50,35,55,25,25,15,205
20,Beautifly,Bug,Flying,60,70,50,100,50,65,395

### Best Pokemon By Total Stats

In [34]:
## Top 30 Pokemon by Total Stats

df.sort_values('Total Stats', ascending = False).head(30)

,Pokemon,Type One,Type Two,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total Stats
Number,,,,,,,,,,
238,Arceus,Normal,NaN,120,120,120,120,120,120,720
235,Dialga,Steel,Dragon,100,120,120,150,100,90,680
237,Giratina Origin,Ghost,Dragon,150,120,100,120,100,90,680
235,Dialga Lord,Steel,Dragon,100,100,120,150,120,90,680
236,Palkia,Water,Dragon,90,120,100,150,120,100,680
236,Palkia Lord,Water,Dragon,90,100,100,150,120,120,680
237,Giratina,Ghost,Dragon,150,100,120,100,120,90,680
229,Regigigas,Normal,NaN,110,160,110,80,110,100,670
233,Landorus,Ground,Flying,89,125,90,115,80,101,600
230,Cresselia,Psychic,NaN,120,70,120,75,130,85,600
228,Heatran,Fire,Steel,91,90,106,130,106,77,600
233,Landorus Therian,Ground,Flying,89,145,90,105,80,91,600
242,Darkrai,Dark,NaN,70,90,90,135,90,125,600
117,Goodra Hisuian,Dragon,Steel,80,100,100,110,150,60,600
241,Shaymin Sky,Grass,Flying,100,103,75,120,75,127,600
240,Manaphy,Water,NaN,100,100,100,100,100,100,600
189,Garchomp,Dragon,Ground,108,130,95,80,85,102,600
241,Shaymin,Grass,NaN,100,100,100,100,100,100,600
231,Tornadus Therian,Flying,NaN,79,100,80,110,90,121,580
227,Azelf,Psychic,NaN,75,125,70,125,70,115,580
232,Thundurus Therian,Electric,Flying,79,105,70,145,80,101,580
231,Tornadus,Flying,NaN,79,115,70,125,80,111,580
232,Thundurus,Electric,Flying,79,115,70,125,80,111,580
234,Enamorus Therian,Fairy,Flying,74,115,110,135,100,46,580
234,Enamorus,Fairy,Flying,74,115,70,135,80,106,580
225,Uxie,Psychic,NaN,75,75,130,75,130,95,580
226,Mesprit,Psychic,NaN,80,105,105,105,105,80,580
151,Arcanine Hisuian,Fire,Rock,95,115,80,95,80,90,555
114,Ursaluna,Normal,Ground,130,140,105,45,80,50,550
129,Togekiss,Fairy,Flying,85,50,95,120,115,80,545

In [35]:
## Top 20 Pokemon Not Arceus, Dialga, Giratina, Palkia, Regigigas, Cresselia, Heatran, Shaymin, 
## Manaphy, Lakes Pokemon, Darkrai, Forces of Nature

legendaries = ['Arceus', 'Dialga', 'Giratina', 'Palkia', 'Regigigas', 'Landorus', 'Tornadus', 
               'Shaymin', 'Azelf', 'Mesprit', 'Uxie', 'Darkrai', 'Cresselia', 'Heatran',
               'Thundurus', 'Enamorus', 'Landorus', 'Giratina Origin', 'Dialga Lord',
               'Enamorus Therian', 'Thundurus Therian', 'Landorus Therian', 
               'Shaymin Sky', 'Palkia Lord', 'Manaphy', 'Tornadus Therian']

In [36]:
legendaries_df = df[df['Pokemon'].isin(legendaries)]

In [37]:
legendaries_df

,Pokemon,Type One,Type Two,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total Stats
Number,,,,,,,,,,
225,Uxie,Psychic,NaN,75,75,130,75,130,95,580
226,Mesprit,Psychic,NaN,80,105,105,105,105,80,580
227,Azelf,Psychic,NaN,75,125,70,125,70,115,580
228,Heatran,Fire,Steel,91,90,106,130,106,77,600
229,Regigigas,Normal,NaN,110,160,110,80,110,100,670
230,Cresselia,Psychic,NaN,120,70,120,75,130,85,600
231,Tornadus,Flying,NaN,79,115,70,125,80,111,580
231,Tornadus Therian,Flying,NaN,79,100,80,110,90,121,580
232,Thundurus,Electric,Flying,79,115,70,125,80,111,580
232,Thundurus Therian,Electric,Flying,79,105,70,145,80,101,580
233,Landorus,Ground,Flying,89,125,90,115,80,101,600
233,Landorus Therian,Ground,Flying,89,145,90,105,80,91,600
234,Enamorus,Fairy,Flying,74,115,70,135,80,106,580
234,Enamorus Therian,Fairy,Flying,74,115,110,135,100,46,580
235,Dialga,Steel,Dragon,100,120,120,150,100,90,680
235,Dialga Lord,Steel,Dragon,100,100,120,150,120,90,680
236,Palkia,Water,Dragon,90,120,100,150,120,100,680
236,Palkia Lord,Water,Dragon,90,100,100,150,120,120,680
237,Giratina,Ghost,Dragon,150,100,120,100,120,90,680
237,Giratina Origin,Ghost,Dragon,150,120,100,120,100,90,680
238,Arceus,Normal,NaN,120,120,120,120,120,120,720
240,Manaphy,Water,NaN,100,100,100,100,100,100,600
241,Shaymin,Grass,NaN,100,100,100,100,100,100,600
241,Shaymin Sky,Grass,Flying,100,103,75,120,75,127,600
242,Darkrai,Dark,NaN,70,90,90,135,90,125,600

In [38]:
not_legendaries_df = df[~df['Pokemon'].isin(legendaries)]

### Best Non-Legendaries

In [39]:
# Best non-legendaries (top 30)

not_legendaries_df.sort_values('Total Stats', ascending = False).head(30)

,Pokemon,Type One,Type Two,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total Stats
Number,,,,,,,,,,
189,Garchomp,Dragon,Ground,108,130,95,80,85,102,600
117,Goodra Hisuian,Dragon,Steel,80,100,100,110,150,60,600
151,Arcanine Hisuian,Fire,Rock,95,115,80,95,80,90,555
114,Ursaluna,Normal,Ground,130,140,105,45,80,50,550
129,Togekiss,Fairy,Flying,85,50,95,120,115,80,545
184,Electivire,Electric,NaN,75,123,67,95,85,95,540
176,Magmortar,Fire,NaN,75,95,67,125,95,83,540
88,Blissey,Normal,NaN,255,10,10,75,135,55,540
52,Snorlax,Normal,NaN,160,110,65,65,110,30,540
81,Gyarados,Water,Flying,95,125,79,60,100,81,540
122,Rhyperior,Ground,Rock,115,140,130,55,55,40,535
96,Tangrowth,Grass,NaN,100,100,125,110,50,50,535
36,Crobat,Poison,Flying,85,90,80,70,80,130,535
179,Magnezone,Electric,Steel,70,70,115,130,90,60,535
135,Porygon Z,Normal,NaN,85,80,70,135,75,90,535
6,Typhlosion Hisuian,Fire,Ghost,73,84,78,119,85,95,534
63,Infernape,Fire,Fighting,76,104,71,104,71,108,534
214,Mamoswine,Ice,Ground,110,130,80,70,60,80,530
145,Walrein,Ice,Water,110,80,90,95,90,65,530
163,Empoleon,Water,Steel,84,86,88,111,101,60,530
167,Basculegion Male,Water,Ghost,120,112,65,80,75,78,530
167,Basculegion Female,Water,Ghost,120,92,65,100,75,78,530
3,Decidueye Hisuian,Grass,Fighting,88,112,80,95,95,60,530
9,Samurott Hisuian,Water,Dark,90,108,80,100,65,85,528
31,Leafeon,Grass,NaN,65,110,130,60,65,95,525
50,Wyrdeer,Normal,Psychic,103,105,72,105,75,65,525
224,Lucario,Fighting,Steel,70,110,70,115,70,90,525
132,Torterra,Grass,Ground,95,109,105,75,85,56,525
191,Probopass,Rock,Steel,60,55,145,75,150,40,525
33,Sylveon,Fairy,NaN,95,65,65,110,130,60,525

### Worst Pokemon By Total Stats

In [40]:
# Worst Pokemon by total stats, top 15:
df.sort_values('Total Stats', ascending = True).head(15)

,Pokemon,Type One,Type Two,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total Stats
Number,,,,,,,,,,
39,Kricketot,Bug,NaN,37,25,41,25,41,25,194
18,Wurmple,Bug,NaN,45,45,35,20,30,20,195
101,Ralts,Psychic,Fairy,28,25,25,45,35,40,198
80,Magikarp,Water,NaN,20,10,55,15,20,80,200
55,Pichu,Electric,NaN,20,40,15,35,35,60,205
21,Cascoon,Bug,NaN,50,35,55,25,25,15,205
19,Silcoon,Bug,NaN,50,35,55,25,25,15,205
199,Cleffa,Fairy,NaN,50,25,28,45,55,15,218
86,Happiny,Normal,NaN,100,5,5,15,65,30,220
43,Burmy Trash,Bug,NaN,40,29,45,29,45,36,224
43,Burmy Sandy,Bug,NaN,40,29,45,29,45,36,224
43,Burmy,Bug,NaN,40,29,45,29,45,36,224
70,Combee,Bug,Flying,30,30,42,30,42,70,244
34,Zubat,Poison,Flying,40,45,35,30,40,55,245
127,Togepi,Fairy,NaN,35,20,65,40,65,20,245

Worst Pokemon by total stats tend to bug Pokemon or small Pokemon.

### Fastest Pokemon Top 15

In [41]:
df.sort_values('Speed', ascending = False).head(15)

,Pokemon,Type One,Type Two,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total Stats
Number,,,,,,,,,,
193,Electrode Hisuian,Electric,Grass,60,50,70,80,80,150,490
27,Jolteon,Electric,NaN,65,65,60,110,95,130,525
36,Crobat,Poison,Flying,85,90,80,70,80,130,535
241,Shaymin Sky,Grass,Flying,100,103,75,120,75,127,600
242,Darkrai,Dark,NaN,70,90,90,135,90,125,600
204,Weavile,Dark,Ice,70,120,65,45,85,125,510
231,Tornadus Therian,Flying,NaN,79,100,80,110,90,121,580
60,Alakazam,Psychic,NaN,55,50,45,135,95,120,500
236,Palkia Lord,Water,Dragon,90,100,100,150,120,120,680
238,Arceus,Normal,NaN,120,120,120,120,120,120,720
203,Sneasler,Poison,Fighting,80,130,60,40,80,120,510
227,Azelf,Psychic,NaN,75,125,70,125,70,115,580
42,Floatzel,Water,NaN,85,105,55,85,50,115,495
202,Sneasel Hisuian,Poison,Fighting,55,95,55,35,75,115,430
202,Sneasel,Dark,Ice,55,95,55,35,75,115,430

### Slowest Pokemon Top 15

In [42]:
df.sort_values('Speed', ascending = True).head(15)

,Pokemon,Type One,Type Two,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total Stats
Number,,,,,,,,,,
51,Munchlax,Normal,NaN,135,85,40,40,85,5,390
123,Bonsly,Rock,NaN,50,80,95,10,45,10,290
21,Cascoon,Bug,NaN,50,35,55,25,25,15,205
19,Silcoon,Bug,NaN,50,35,55,25,25,15,205
199,Cleffa,Fairy,NaN,50,25,28,45,55,15,218
18,Wurmple,Bug,NaN,45,45,35,20,30,20,195
127,Togepi,Fairy,NaN,35,20,65,40,65,20,245
46,Geodude,Rock,Ground,40,80,100,30,30,20,300
180,Bronzor,Steel,Psychic,57,24,86,24,86,23,300
39,Kricketot,Bug,NaN,37,25,41,25,41,25,194
143,Spheal,Ice,Water,70,40,50,55,50,25,290
53,Paras,Bug,Grass,35,70,55,45,55,25,285
159,Dusclops,Ghost,NaN,40,70,130,60,130,25,455
158,Duskull,Ghost,NaN,20,40,90,30,90,25,295
120,Rhyhorn,Ground,Rock,80,85,95,30,30,25,345

### Best Attacking Pokemon Top 15

In [43]:
df.sort_values('Attack', ascending = False).head(15)

,Pokemon,Type One,Type Two,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total Stats
Number,,,,,,,,,,
209,Rampardos,Rock,NaN,97,165,60,65,50,58,495
229,Regigigas,Normal,NaN,110,160,110,80,110,100,670
233,Landorus Therian,Ground,Flying,89,145,90,105,80,91,600
122,Rhyperior,Ground,Rock,115,140,130,55,55,40,535
114,Ursaluna,Normal,Ground,130,140,105,45,80,50,550
73,Kleavor,Bug,Rock,70,135,95,45,70,85,500
156,Machamp,Fighting,NaN,90,130,80,65,85,55,505
113,Ursaring,Normal,NaN,90,130,75,75,75,55,500
121,Rhydon,Ground,Rock,105,130,120,45,45,40,485
189,Garchomp,Dragon,Ground,108,130,95,80,85,102,600
203,Sneasler,Poison,Fighting,80,130,60,40,80,120,510
214,Mamoswine,Ice,Ground,110,130,80,70,60,80,530
28,Flareon,Fire,NaN,65,130,60,95,110,65,525
74,Scizor,Bug,Steel,70,130,100,55,80,65,500
216,Avalugg Hisuian,Ice,Rock,95,127,184,34,36,38,514

### Best Defensive Pokemon Top 15

In [44]:
df.sort_values('Defense', ascending = False).head(15)

,Pokemon,Type One,Type Two,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total Stats
Number,,,,,,,,,,
119,Steelix,Steel,Ground,75,85,200,55,65,30,510
216,Avalugg Hisuian,Ice,Rock,95,127,184,34,36,38,514
211,Bastiodon,Rock,Steel,60,52,168,47,138,30,495
118,Onix,Rock,Ground,35,45,160,30,45,70,385
191,Probopass,Rock,Steel,60,55,145,75,150,40,525
160,Dusknoir,Ghost,NaN,45,100,135,65,135,45,525
190,Nosepass,Rock,NaN,30,45,135,45,90,30,375
31,Leafeon,Grass,NaN,65,110,130,60,65,95,525
122,Rhyperior,Ground,Rock,115,140,130,55,55,40,535
159,Dusclops,Ghost,NaN,40,70,130,60,130,25,455
225,Uxie,Psychic,NaN,75,75,130,75,130,95,580
48,Golem,Rock,Ground,80,120,130,55,65,45,495
186,Gliscor,Ground,Flying,75,95,125,45,75,95,510
96,Tangrowth,Grass,NaN,100,100,125,110,50,50,535
121,Rhydon,Ground,Rock,105,130,120,45,45,40,485

### Top 15 Special Attackers

In [45]:
df.sort_values('Sp. Atk', ascending = False).head(15)

,Pokemon,Type One,Type Two,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total Stats
Number,,,,,,,,,,
236,Palkia,Water,Dragon,90,120,100,150,120,100,680
236,Palkia Lord,Water,Dragon,90,100,100,150,120,120,680
235,Dialga,Steel,Dragon,100,120,120,150,100,90,680
235,Dialga Lord,Steel,Dragon,100,100,120,150,120,90,680
232,Thundurus Therian,Electric,Flying,79,105,70,145,80,101,580
234,Enamorus,Fairy,Flying,74,115,70,135,80,106,580
60,Alakazam,Psychic,NaN,55,50,45,135,95,120,500
234,Enamorus Therian,Fairy,Flying,74,115,110,135,100,46,580
242,Darkrai,Dark,NaN,70,90,90,135,90,125,600
135,Porygon Z,Normal,NaN,85,80,70,135,75,90,535
29,Espeon,Psychic,NaN,65,65,60,130,95,110,525
32,Glaceon,Ice,NaN,65,60,110,130,95,65,525
228,Heatran,Fire,Steel,91,90,106,130,106,77,600
138,Gengar,Ghost,Poison,60,65,60,130,75,110,500
179,Magnezone,Electric,Steel,70,70,115,130,90,60,535

### Top 15 Special Defenders

In [46]:
df.sort_values('Sp. Def', ascending = False).head(15)

,Pokemon,Type One,Type Two,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total Stats
Number,,,,,,,,,,
117,Goodra Hisuian,Dragon,Steel,80,100,100,110,150,60,600
191,Probopass,Rock,Steel,60,55,145,75,150,40,525
165,Mantine,Water,Flying,85,40,70,80,140,70,485
211,Bastiodon,Rock,Steel,60,52,168,47,138,30,495
88,Blissey,Normal,NaN,255,10,10,75,135,55,540
160,Dusknoir,Ghost,NaN,45,100,135,65,135,45,525
33,Sylveon,Fairy,NaN,95,65,65,110,130,60,525
225,Uxie,Psychic,NaN,75,75,130,75,130,95,580
159,Dusclops,Ghost,NaN,40,70,130,60,130,25,455
30,Umbreon,Dark,NaN,95,65,110,60,130,65,525
230,Cresselia,Psychic,NaN,120,70,120,75,130,85,600
164,Mantyke,Water,Flying,45,20,50,60,120,50,345
77,Mr. Mime,Psychic,Fairy,40,45,65,100,120,90,460
171,Tentacruel,Water,Poison,80,70,65,80,120,100,515
235,Dialga Lord,Steel,Dragon,100,100,120,150,120,90,680